name = "Taiga"
uuid = "e9eb81f5-0267-4fb6-9dbb-4fd71c34045d"
version = "0.7.1"
authors = ["Micha≈Ç Mika <michal@mika.sh>"]

[deps]
AbstractMappings = "7dac2afd-1bf6-47b8-bc94-9dcdcd19d527"
Algoim = "0eb9048c-21de-4c7a-bfac-056de1940b74"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CartesianProducts = "ddfd9c64-15e7-45fc-8e16-950f3835cae5"
CatViews = "81a5f4ea-a946-549a-aa7e-2a7f63a27d31"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IgaBase = "9c103fa8-ae55-49f5-92db-ab77803cf2c4"
IgaFormation = "3811570c-b24d-4931-9f1c-72ee5a79a1d1"
ImmersedSplines = "3e3b8edd-9419-4511-a852-83e823fd4317"
ImplicitGeometries = "95516d86-82af-438a-ae84-b941c80ea631"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KroneckerProducts = "5766f8de-d509-470a-8420-f491b24ab91b"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NURBS = "3119edd0-0685-4064-9500-10252e0e5727"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SortedSequences = "2f2e3dc8-c2cf-4b7f-b456-36845a1cbdbc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SpecialSpaces = "cc3e65be-d4cb-4562-9ae2-5262579a9956"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SuiteSplines = "c1439797-f1c6-466c-87a0-2eb89882a10c"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TensorProductBsplines = "89f2e70f-f704-4f07-9b81-69bdc44074b1"
TensorToolbox = "9c690861-8ade-587a-897e-15364bc6f718"
UnivariateSplines = "2552f6ce-f0d6-4ba3-bf39-bb338613ee69"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
IgaFormation = "0.6"
NURBS = "^0.12.0"

[extras]
CartesianProducts = "ddfd9c64-15e7-45fc-8e16-950f3835cae5"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KroneckerProducts = "5766f8de-d509-470a-8420-f491b24ab91b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SortedSequences = "2f2e3dc8-c2cf-4b7f-b456-36845a1cbdbc"
SpecialSpaces = "cc3e65be-d4cb-4562-9ae2-5262579a9956"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorProductBsplines = "89f2e70f-f704-4f07-9b81-69bdc44074b1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnivariateSplines = "2552f6ce-f0d6-4ba3-bf39-bb338613ee69"

[targets]
test = ["Test", "SafeTestsets", "JLD2", "LinearAlgebra", "CartesianProducts", "ForwardDiff", "SortedSequences", "UnivariateSplines", "KroneckerProducts", "TensorProductBsplines", "Documenter", "Statistics", "SpecialSpaces"]
